name: Auto Deploy Veramon Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
        
    - name: Create mock .env file for testing
      run: |
        echo "BOT_TOKEN=mock_token_for_ci" > .env
        echo "COMMAND_PREFIX=!" >> .env
        echo "DATABASE_PATH=data/veramon_reunited.db" >> .env
        echo "DEBUG_MODE=True" >> .env
        echo "MAINTENANCE_MODE=False" >> .env
        echo "LOG_LEVEL=INFO" >> .env
        
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        
    - name: Test with pytest
      continue-on-error: true
      run: |
        pip install pytest
        if [ -d tests ]; then pytest -v; fi
  
  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set current date
      id: date
      run: echo "BUILD_DATE=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/veramon-bot:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/veramon-bot:${{ env.BUILD_DATE }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ github.event.inputs.environment || 'production' }}
    
    steps:
    - name: Deploy to server using sshpass
      uses: actions/checkout@v3  # Just to get a workspace
      
    - name: Install sshpass
      run: sudo apt-get install -y sshpass
      
    - name: Deploy via SSH with password
      run: |
        # Create deployment script
        cat > deploy.sh << EOF
        #!/bin/bash
        # Create deployment directory if needed
        mkdir -p ${{ secrets.DEPLOY_PATH }}
        cd ${{ secrets.DEPLOY_PATH }}
        
        # Backup previous .env file if it exists
        if [ -f .env ]; then
          cp .env .env.backup
        else
          # Create .env file if it doesn't exist
          cat > .env << 'ENVEOF'
        BOT_TOKEN=${{ secrets.BOT_TOKEN }}
        COMMAND_PREFIX=!
        DATABASE_PATH=data/veramon_reunited.db
        DEBUG_MODE=False
        MAINTENANCE_MODE=False
        LOG_LEVEL=INFO
        ENVEOF
        fi
        
        # Create necessary directories for all systems
        mkdir -p data logs battle-system battle-trading factions events quests tournaments
        chmod -R 777 data logs battle-system battle-trading factions events quests tournaments
        
        # Download the latest docker-compose file
        wget -O docker-compose.yml https://raw.githubusercontent.com/${{ github.repository }}/main/docker/docker-compose.yml
        
        # Pull the new image
        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/veramon-bot:latest
        
        # Restart the container
        docker-compose down || true
        docker-compose up -d
        
        # Check if the bot is running properly
        sleep 10
        if ! docker ps | grep veramon-bot; then
          echo "Error: Bot failed to start"
          docker logs veramon-bot --tail 50
          exit 1
        fi
        
        # Clean up old images
        docker image prune -af --filter "until=24h"
        
        echo "Deployment successful!"
        EOF
        
        chmod +x deploy.sh
        
        # Use sshpass to copy and execute the script
        export SSHPASS=${{ secrets.SERVER_PASSWORD }}
        sshpass -e scp -o StrictHostKeyChecking=no deploy.sh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/tmp/deploy.sh
        sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "bash /tmp/deploy.sh"
